In [175]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import sys
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.svm import SVC

In [182]:
data_labelled = pd.read_csv('monthly-data-labelled.csv')
data_unlabelled = pd.read_csv('monthly-data-unlabelled.csv')
#Xnew=np.array(data_unlabelled)
y=data_labelled['city']
X=data_labelled[data_labelled.columns[2:62]]
Xnew=data_unlabelled[data_unlabelled.columns[2:62]]
Xnew

,tmax-01,tmax-02,tmax-03,tmax-04,tmax-05,tmax-06,tmax-07,tmax-08,tmax-09,tmax-10,...,snwd-03,snwd-04,snwd-05,snwd-06,snwd-07,snwd-08,snwd-09,snwd-10,snwd-11,snwd-12
0,234.935484,240.793103,285.677419,288.133333,303.000000,322.600000,328.580645,324.806452,323.000000,302.741935,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,76.806452,100.571429,115.677419,156.966667,185.322581,201.800000,220.333333,223.000000,179.566667,137.354839,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,4.838710
2,63.677419,112.620690,127.387097,152.033333,193.903226,296.966667,333.354839,301.419355,279.266667,235.774194,...,20.000000,15.333333,0.0,0.0,0.0,0.0,0.0,0.000000,1.666667,23.548387
3,94.741935,119.724138,135.709677,188.300000,204.677419,228.300000,244.290323,264.193548,208.666667,158.612903,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.967742
4,63.129032,85.689655,145.000000,163.500000,205.064516,275.600000,304.580645,311.290323,267.933333,201.935484,...,1.935484,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
5,89.774194,119.413793,207.935484,223.333333,250.741935,307.533333,332.838710,332.645161,296.933333,240.354839,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
6,106.354839,144.241379,213.387097,234.233333,273.709677,328.966667,341.967742,330.645161,312.466667,272.709677,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
7,84.516129,135.793103,142.096774,202.766667,223.870968,248.733333,261.612903,291.903226,234.100000,168.290323,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,5.666667
8,138.870968,184.206897,177.032258,200.033333,202.096774,222.200000,216.709677,216.193548,230.900000,213.838710,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
9,-0.967742,29.206897,108.258065,141.233333,211.419355,277.233333,291.225806,290.483871,253.666667,188.000000,...,2.903226,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,61.290323
10,-0.096774,20.103448,48.129032,108.566667,155.032258,193.566667,206.064516,193.032258,147.200000,62.774194,...,19.354839,0.000000,0.0,0.0,0.0,0.0,0.0,15.806452,2.000000,250.000000
11,177.967742,230.000000,194.741935,215.266667,198.935484,224.586207,252.258065,244.935484,254.100000,241.935484,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000

In [183]:
X_train,X_valid,y_train,y_valid=train_test_split(X,y)

In [184]:
#model=VotingClassifier([
#   ('nb',GaussianNB()),
#   ('knn',KNeighborsClassifier(5)),
#   ('svm',SVC(kernel='linear',C=0.1)),
#])
#The above one 
model=make_pipeline(
    StandardScaler(),
    SVC(kernel='linear',C=0.1)
    )

In [185]:
model.fit(X_train,y_train)
print(model.score(X_valid,y_valid))

0.8103448275862069

In [186]:
predictions=model.predict(Xnew)

In [187]:
#pd.Series(predictions).to_csv(sys.argv[3], index=False, header=False)
pd.Series(predictions).to_csv('labels.csv', index=False, header=False)